create type public.exam_status as enum ('draft', 'published');

create table public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  exam_id bigint,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

alter table public.exams
  add column status public.exam_status not null default 'draft',
  add column published_at timestamptz,
  add column updated_at timestamptz not null default now();

alter table public.exam_subjects
  add column question_pdf_path text,
  add column explanation_pdf_path text;

update public.exam_subjects exam_subject
set question_pdf_path = exam.question_pdf_path,
    explanation_pdf_path = exam.explanation_pdf_path
from public.exams exam
where exam.id = exam_subject.exam_id;

alter table public.exams
  drop column question_pdf_path,
  drop column explanation_pdf_path;

create trigger exams_set_updated_at before update on public.exams
for each row execute function public.set_updated_at();

alter table public.admin_users enable row level security;
alter table public.admin_audit_logs enable row level security;

create policy "Admins can read their membership" on public.admin_users
for select to authenticated using (user_id = (select auth.uid()));
create policy "Admins can read audit logs" on public.admin_audit_logs
for select to authenticated using ((select public.is_admin()));
create policy "Admins can create audit logs" on public.admin_audit_logs
for insert to authenticated with check ((select public.is_admin()) and admin_user_id = (select auth.uid()));

drop policy "Authenticated users can read exams" on public.exams;
drop policy "Authenticated users can read exam subjects" on public.exam_subjects;
drop policy "Authenticated users can read answer keys" on public.answer_keys;

create policy "Users can read published exams" on public.exams
for select to authenticated using (status = 'published' or (select public.is_admin()));
create policy "Admins can create exams" on public.exams
for insert to authenticated with check ((select public.is_admin()));
create policy "Admins can update exams" on public.exams
for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "Admins can delete exams" on public.exams
for delete to authenticated using ((select public.is_admin()));

create policy "Users can read published exam subjects" on public.exam_subjects
for select to authenticated using (
  (select public.is_admin()) or exists (
    select 1 from public.exams exam
    where exam.id = exam_id and exam.status = 'published'
  )
);
create policy "Admins can create exam subjects" on public.exam_subjects
for insert to authenticated with check ((select public.is_admin()));
create policy "Admins can update exam subjects" on public.exam_subjects
for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "Admins can delete exam subjects" on public.exam_subjects
for delete to authenticated using ((select public.is_admin()));

create policy "Users can read published answer keys" on public.answer_keys
for select to authenticated using (
  (select public.is_admin()) or exists (
    select 1
    from public.exam_subjects exam_subject
    join public.exams exam on exam.id = exam_subject.exam_id
    where exam_subject.id = exam_subject_id and exam.status = 'published'
  )
);
create policy "Admins can create answer keys" on public.answer_keys
for insert to authenticated with check ((select public.is_admin()));
create policy "Admins can update answer keys" on public.answer_keys
for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "Admins can delete answer keys" on public.answer_keys
for delete to authenticated using ((select public.is_admin()));

drop policy "Users can read their attempts" on public.attempts;
create policy "Users can read their attempts" on public.attempts
for select to authenticated using ((select auth.uid()) = user_id or (select public.is_admin()));

drop policy "Authenticated users can read exam PDFs" on storage.objects;
create policy "Users can read published exam PDFs" on storage.objects
for select to authenticated using (
  bucket_id = 'exam-pdfs' and (
    (select public.is_admin()) or exists (
      select 1
      from public.exam_subjects exam_subject
      join public.exams exam on exam.id = exam_subject.exam_id
      where exam.status = 'published'
        and (exam_subject.question_pdf_path = name or exam_subject.explanation_pdf_path = name)
    )
  )
);
create policy "Admins can upload exam PDFs" on storage.objects
for insert to authenticated with check (bucket_id = 'exam-pdfs' and (select public.is_admin()));
create policy "Admins can update exam PDFs" on storage.objects
for update to authenticated using (bucket_id = 'exam-pdfs' and (select public.is_admin())) with check (bucket_id = 'exam-pdfs' and (select public.is_admin()));
create policy "Admins can delete exam PDFs" on storage.objects
for delete to authenticated using (bucket_id = 'exam-pdfs' and (select public.is_admin()));

update storage.buckets
set public = false,
    file_size_limit = 52428800,
    allowed_mime_types = array['application/pdf']::text[]
where id = 'exam-pdfs';

grant select on public.admin_users to authenticated;
grant select, insert on public.admin_audit_logs to authenticated;
grant insert, update, delete on public.exams, public.exam_subjects, public.answer_keys to authenticated;
grant usage, select on sequence public.admin_audit_logs_id_seq to authenticated;
