create table public.answer_key_reports (
  id bigint generated by default as identity primary key,
  exam_subject_id bigint not null references public.exam_subjects(id) on delete cascade,
  reporter_user_id uuid references auth.users(id) on delete set null,
  question_number integer not null check (question_number between 1 and 45),
  issue_type text not null check (issue_type in ('answer', 'points', 'both', 'other')),
  details text not null default '' check (char_length(details) <= 1000),
  status text not null default 'open' check (status in ('open', 'resolved', 'dismissed')),
  resolved_by uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index answer_key_reports_one_open_per_question_idx
on public.answer_key_reports (exam_subject_id, reporter_user_id, question_number)
where status = 'open';

create index answer_key_reports_status_created_at_idx
on public.answer_key_reports (status, created_at desc);

create index answer_key_reports_exam_subject_id_idx
on public.answer_key_reports (exam_subject_id);

create trigger answer_key_reports_set_updated_at before update on public.answer_key_reports
for each row execute function public.set_updated_at();

alter table public.answer_key_reports enable row level security;

create policy "Users can read their answer key reports" on public.answer_key_reports
for select to authenticated using (
  reporter_user_id = (select auth.uid()) or (select public.is_admin())
);

create policy "Users can report published answer keys" on public.answer_key_reports
for insert to authenticated with check (
  reporter_user_id = (select auth.uid())
  and status = 'open'
  and resolved_by is null
  and resolved_at is null
  and exists (
    select 1
    from public.exam_subjects exam_subject
    join public.subjects subject on subject.id = exam_subject.subject_id
    where exam_subject.id = exam_subject_id
      and exam_subject.status = 'published'
      and question_number <= subject.question_count
  )
);

create policy "Admins can update answer key reports" on public.answer_key_reports
for update to authenticated using ((select public.is_admin()))
with check ((select public.is_admin()));

grant select, insert, update on public.answer_key_reports to authenticated;
grant usage, select on sequence public.answer_key_reports_id_seq to authenticated;
grant select on public.answer_key_reports to service_role;
