create extension if not exists pgcrypto;

create type public.attempt_status as enum ('new', 'doing', 'done');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  theme text not null default 'system' check (theme in ('light', 'dark', 'system')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.subjects (
  id bigint generated by default as identity primary key,
  area text not null,
  name text not null unique,
  question_count integer not null check (question_count > 0),
  duration_seconds integer not null check (duration_seconds > 0),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.exams (
  id bigint generated by default as identity primary key,
  year integer not null check (year between 1994 and 2100),
  month integer not null check (month between 1 and 12),
  title text not null,
  question_url text,
  explanation_url text,
  is_development_data boolean not null default false,
  created_at timestamptz not null default now(),
  unique (year, month, title)
);

create table public.exam_subjects (
  id bigint generated by default as identity primary key,
  exam_id bigint not null references public.exams(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (exam_id, subject_id)
);

create table public.answer_keys (
  id bigint generated by default as identity primary key,
  exam_subject_id bigint not null references public.exam_subjects(id) on delete cascade,
  question_number integer not null check (question_number > 0),
  answer text not null,
  points integer not null check (points > 0),
  unique (exam_subject_id, question_number)
);

create table public.user_shortcuts (
  user_id uuid not null references auth.users(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, subject_id)
);

create table public.attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  exam_subject_id bigint not null references public.exam_subjects(id) on delete cascade,
  answers jsonb not null default '{}'::jsonb check (jsonb_typeof(answers) = 'object'),
  status public.attempt_status not null default 'doing',
  score integer check (score is null or score >= 0),
  remaining_seconds integer check (remaining_seconds is null or remaining_seconds >= 0),
  graded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, exam_subject_id)
);

create index attempts_user_id_idx on public.attempts(user_id);
create index exam_subjects_subject_id_idx on public.exam_subjects(subject_id);
create index answer_keys_exam_subject_id_idx on public.answer_keys(exam_subject_id);

create or replace function public.set_updated_at()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();
create trigger attempts_set_updated_at before update on public.attempts
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)));
  return new;
end;
$$;

create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

insert into public.profiles (id, display_name)
select id, coalesce(raw_user_meta_data ->> 'display_name', raw_user_meta_data ->> 'full_name', split_part(email, '@', 1))
from auth.users
on conflict (id) do nothing;

alter table public.profiles enable row level security;
alter table public.subjects enable row level security;
alter table public.exams enable row level security;
alter table public.exam_subjects enable row level security;
alter table public.answer_keys enable row level security;
alter table public.user_shortcuts enable row level security;
alter table public.attempts enable row level security;

create policy "Users can read their profile" on public.profiles for select to authenticated using ((select auth.uid()) = id);
create policy "Users can update their profile" on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
create policy "Authenticated users can read subjects" on public.subjects for select to authenticated using (true);
create policy "Authenticated users can read exams" on public.exams for select to authenticated using (true);
create policy "Authenticated users can read exam subjects" on public.exam_subjects for select to authenticated using (true);
create policy "Authenticated users can read answer keys" on public.answer_keys for select to authenticated using (true);
create policy "Users can read their shortcuts" on public.user_shortcuts for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can create their shortcuts" on public.user_shortcuts for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users can delete their shortcuts" on public.user_shortcuts for delete to authenticated using ((select auth.uid()) = user_id);
create policy "Users can read their attempts" on public.attempts for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can create their attempts" on public.attempts for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users can update their attempts" on public.attempts for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Users can delete their attempts" on public.attempts for delete to authenticated using ((select auth.uid()) = user_id);

grant usage on schema public to authenticated;
grant select on public.subjects, public.exams, public.exam_subjects, public.answer_keys to authenticated;
grant select, update on public.profiles to authenticated;
grant select, insert, delete on public.user_shortcuts to authenticated;
grant select, insert, update, delete on public.attempts to authenticated;
grant usage, select on all sequences in schema public to authenticated;
